# Generated by Django 3.1.5 on 2021-01-05 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tName', models.CharField(max_length=50, null=True, unique=True)),
                ('username', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'NewsType',
            },
        ),
        migrations.CreateModel(
            name='NewsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nTitle', models.CharField(max_length=100, null=True)),
                ('nAuthor', models.CharField(max_length=20, null=True)),
                ('nContent', models.CharField(max_length=1000, null=True)),
                ('nPubDateTime', models.DateTimeField(auto_now_add=True)),
                ('Nstatus', models.BooleanField()),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.newstype')),
            ],
            options={
                'db_table': 'NewsInfo',
            },
        ),
    ]
